### ISSUE TITLE
The Properties of Message Objects are currently useless

### ISSUE THREAD

**Issue by Bramas** [acasteigts/JBotSim#10]
A `Message` inherit from `_Properties` but everytime a message is copied, the properties are not copied (only the content).
And message are copied very often, for instance, every time we send a message, it is copied.
So we cannot assign property to messages because the properties will be lost.

So we have two possibilities. 
1. Either we remove the fact the Message inherit from _Properties to avoid confusion (I don't think someone use it since it is useless right now)
1. Or we change the copy constructor of Message to also copy the properties.

I like the first case since Message becomes truly immutable.
However I have some use case where I wanted to add a property to a message (to have something like a flag), so I implemented the second method and **it worked well**.

Maybe the right way is to remove the _Properties inheritance and add an immutable attribut (like `flag` or `tag`) so that Message are truly immutable **and** we can still attach some information to it

What do you think?

**Comment by acasteigts** [comment]
Well, thank you for noticing that the properties are not copied! 
The initial motivation was to enable structured messages at low cost, e.g. a composite message that contains several objects. A second one was to enable more specialized message engine (such as the ones in jbotsimx.messaging). However, as you point out, if the non-copy bug was never noticed so far, then it is likely that no one is using this feature. OK in principle to remove it.

Before changing the code, can you please provide an example of flag that you are using? Just curious...

**Comment by Bramas** [comment]
In my fork, I didn't removed the properties (and I changed the copy constructor of Message so that it copies the properties). But I used the property as a flag.
When I receive a message I check and do different things whether the message has a property or not. that's why I think we can replace properties by simply a flag attribut. But maybe its not necessary to remove properties, because what I said earlier about making messages immutable is not entirely true since the content of a message may not be an immutable object.
Anyway we can remove or keep properties (but then copy the properties when we copy a message) as you want and still add the flag attribut (or we can call it tag or even type)

A good example is to take your tutorial on distributed tree construction http://www.labri.fr/perso/acasteig/teaching/algomob/practice/spanning-tree.html

You say that, we can inherit from TreeNode to create a new kind of node that automatically forms a tree, and since other messages can be sent, `TreeNode` must check the content of the messages it receives with this line.
```java
if (message.getContent() instanceof Node)
```

Using a flag here is safer.

```java
If(message.getFlag().equals("TreeNode"))
```

Of course we have to add the flag to all messages sent by TreeNode and we are done
```java
Message m = new Message(content, "TreeNode");
```

Since message is immutable, we cannot modify a message to add a flag but we can do something like this.

```java
Message m = new Message(content);
m = m.withFlag("SomeFlag");
```

We can even create a copy method like this (to replace juste the destination of a message)
```java
m = m.to(destination);
```

Ultimately, flag can be used to associate message type with the corresponding function:
```java
Switch(m.getFlag()){
  case "TreeNodeInit": initalizeTree(m); break;
  case  "TreeNodeControl" : controlTree(m); break;
  /* ... */
}
```

but again, maybe its simpler to just keep the properties, and change the copy constructor to copy the properties too (as I said in my fork). As you want.

**Comment by acasteigts** [comment]
Nice. For now, the more reasonable seems to keep the properties (and fix the copy as you suggest) and we can add a String flag. The use of the flag should remain optional, so in the current constructor we may use the class name as default tag value (as you do above). Then add a new constructor with flag parameter, as well as a getFlag() method as you suggest. I don't feel like adding a withFlag method to generate a flagged version of an existing message is relevant, but I may miss something. Unless you have reasons for this, I suggest to stick with setting the flag on construction only for now and see with time if more is needed. 

What do you think?

Regarding terminology, is there a subtle difference of meaning between what is commonly referred to as a "tag" or a "flag" ? (let apart type) I feel like flag is more natural for this, but with no conviction.
