### ISSUE TITLE
Strange assert in Message.java

### ISSUE THREAD

**Issue by egodardlif** [acasteigts/JBotSim#12]
When run with` -enableassertions`, Message creation always fails
```
 public Message(Object content){    
     this(null, null, content);
     }
  Message(Node sender, Node destination, Object content){
         assert(destination!=null);
         this.sender = sender;
         this.destination=destination;
         this.content=content;
     }
```
Is the` assert `necessary here ?

**Comment by Bramas** [comment]
No you are right, I will remove it in a future pull request (I will add copy the properties when cloning messages, see the corresponding issue)

**Comment by acasteigts** [comment]
You are right. This must have pre-existed the empty constructor... Incidentally, I thought that assertions were enabled by default. So Quentin you take care of this? Thanks (to both)
