### ISSUE TITLE
Competitive access to running variable in DefaultClock

### ISSUE THREAD

**Issue by darrivau** [acasteigts/JBotSim#20]
The "running" variable of DefaultClock is changed by the main thread through "start()", "pause()" or "resume()" and read by the timer thread through "run()". In the "run()" method, the timer thread caches the variable state and even if the main thread do change its value, the timer thread can keep the wrong one in its cache.
To avoid this problem just add "volatile" attribute to the "running" variable :
```
public class DefaultClock extends Clock implements Runnable{
volatile boolean running;
```

**Comment by remikey** [comment]
Applied in https://github.com/acasteigts/JBotSim/commit/4081ba8a0d20cc78c52dc75fbec3ec7a09c6779a .
Travis ok https://travis-ci.org/acasteigts/JBotSim/builds/432825478

**Comment by darrivau** [comment]
Davis integration tests on commit #aab1dc495983aef2 failed 4 times over 5 by time out. One test is freezing just after starting. When I apply the beta3 patch with the "volatile" correction, the integration tests passed 5 times over 5.

**Comment by remikey** [comment]
The actual commit number is now fe8dc964c74b262c322354eb23c26f69ca720d23 .
Merged by @acasteigts and published in beta03.
