### ISSUE TITLE
Default node icon

### ISSUE THREAD

**Issue by pictavien** [acasteigts/JBotSim#36]
Hi,

The default icon used to display nodes is the resource /io/jbotsim/ui/circle.png. 
If we create a collection/library of icons, perhaps this file could be renamed "default-node-icon.png" 
or something like that.

**Comment by remikey** [comment]
I think it's a good idea to have some kind of "default-something.png".
@acasteigts, should we duplicate circle.png during #26 in order to keep the reference ot "circle"?

**Comment by acasteigts** [comment]
Good idea, and yes, duplication seems appropriate.

**Comment by remikey** [comment]
Closing this conversation and adding result to #26 .
